android.useAndroidX=true
android.enableJetifier=true

org.gradle.jvmargs=-Xmx512m -Dfile.encoding=UTF-8

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=2
org.gradle.configureondemand=true

android.javaCompile.suppressSourceTargetDeprecationWarning=true

# aapt2 dari sistem (mesin aarch64; aapt2 Maven hanya tersedia untuk x86_64)
android.aapt2FromMavenOverride=/usr/bin/aapt2

# debug, lifecycle, info, warn, quiet
org.gradle.logging.level=lifecycle

org.gradle.console=auto